log:
  level: Debug

# allowed to use hexo statistics domain
statistics:
  site:
    - xcmaster.com
    - localhost:4000

# cors domains
cors:
  origins:
    - https://xcmaster.com
    - http://localhost:4000
  methods:
    - GET
    - POST

# redis config
redis:
  address: 127.0.0.1:6379
  password:
  timeout: 3000 # timeout in milliseconds