name: Build Image and Publish to Dockerhub & GPR

on:
  release:
    types: [ edited ]
#   workflow_dispatch:
#     inputs:
#       tag:
#         description: 'Image tag'
#         required: true
#         default: 'test'
jobs:
  image:
    name: Build Image from Dockerfile and binaries
    runs-on: ubuntu-latest
    steps:
      # environment
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v2
#        with:
#          platforms: linux/amd64,linux/arm64
#          platforms: linux/amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # get image tag name
      - name: Get Image Tag Name
        run: |
          if [ x${{ github.event.inputs.tag }} == x"" ]; then
            echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          else
            echo "TAG_NAME=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          fi

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to the GPR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # prepare image tags
      - name: Prepare Image Tags
        run: |
          echo "DOCKERFILE_PATH=Dockerfile" >> $GITHUB_ENV
          echo "DOCKER_TAG=stulzq/hexo-statistics:${{ env.TAG_NAME }}" >> $GITHUB_ENV
          echo "DOCKER_GPR_TAG=ghcr.io/stulzq/hexo-statistics:${{ env.TAG_NAME }}" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
#          platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.DOCKER_TAG }}
            ${{ env.DOCKER_GPR_TAG }}
